"""auto update

Revision ID: 56a72799854f
Revises: ed8588395a22
Create Date: 2026-08-21 08:45:32.314294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a72799854f'
down_revision: Union[str, Sequence[str], None] = 'ed8588395a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_upload_limits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('max_audio_minutes', sa.Integer(), nullable=True),
    sa.Column('max_audio_mb', sa.Integer(), nullable=True),
    sa.Column('max_attachment_mb', sa.Integer(), nullable=True),
    sa.Column('updated_by_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_upload_limits_id'), 'org_upload_limits', ['id'], unique=False)
    op.create_index(op.f('ix_org_upload_limits_organization_id'), 'org_upload_limits', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_upload_limits_organization_id'), table_name='org_upload_limits')
    op.drop_index(op.f('ix_org_upload_limits_id'), table_name='org_upload_limits')
    op.drop_table('org_upload_limits')
    # ### end Alembic commands ###