"""auto update

Revision ID: 6fd0481888ea
Revises: 56a72799854f
Create Date: 2026-08-21 09:25:19.295735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd0481888ea'
down_revision: Union[str, Sequence[str], None] = '56a72799854f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_archive_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('source_kind', sa.String(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('source_bucket', sa.String(), nullable=True),
    sa.Column('source_object_key', sa.String(), nullable=True),
    sa.Column('remote_path', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum_sha256', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('archived_at', sa.String(), nullable=True),
    sa.Column('restored_at', sa.String(), nullable=True),
    sa.Column('restore_expires_at', sa.String(), nullable=True),
    sa.Column('archived_by_name', sa.String(), nullable=True),
    sa.Column('restored_by_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_archive_files_id'), 'meeting_archive_files', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_archive_files_meeting_id'), 'meeting_archive_files', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_archive_files_organization_id'), 'meeting_archive_files', ['organization_id'], unique=False)
    op.create_index(op.f('ix_meeting_archive_files_source_id'), 'meeting_archive_files', ['source_id'], unique=False)
    op.create_table('org_storage_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('bucket', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('path_prefix', sa.String(), nullable=True),
    sa.Column('access_key', sa.String(), nullable=True),
    sa.Column('secret_key_enc', sa.String(), nullable=True),
    sa.Column('force_path_style', sa.Boolean(), nullable=True),
    sa.Column('webdav_base_url', sa.String(), nullable=True),
    sa.Column('webdav_username', sa.String(), nullable=True),
    sa.Column('webdav_password_enc', sa.String(), nullable=True),
    sa.Column('restore_retention_days', sa.Integer(), nullable=True),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.Column('last_test_at', sa.String(), nullable=True),
    sa.Column('last_test_message', sa.String(), nullable=True),
    sa.Column('updated_by_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_storage_targets_id'), 'org_storage_targets', ['id'], unique=False)
    op.create_index(op.f('ix_org_storage_targets_organization_id'), 'org_storage_targets', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_storage_targets_organization_id'), table_name='org_storage_targets')
    op.drop_index(op.f('ix_org_storage_targets_id'), table_name='org_storage_targets')
    op.drop_table('org_storage_targets')
    op.drop_index(op.f('ix_meeting_archive_files_source_id'), table_name='meeting_archive_files')
    op.drop_index(op.f('ix_meeting_archive_files_organization_id'), table_name='meeting_archive_files')
    op.drop_index(op.f('ix_meeting_archive_files_meeting_id'), table_name='meeting_archive_files')
    op.drop_index(op.f('ix_meeting_archive_files_id'), table_name='meeting_archive_files')
    op.drop_table('meeting_archive_files')
    # ### end Alembic commands ###