"""auto update

Revision ID: 830baecb4a38
Revises: c8be0665f561
Create Date: 2026-08-19 03:37:02.528650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '830baecb4a38'
down_revision: Union[str, Sequence[str], None] = 'c8be0665f561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('mobile', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('national_id', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_users_id'), 'app_users', ['id'], unique=False)
    op.create_index(op.f('ix_app_users_national_id'), 'app_users', ['national_id'], unique=False)
    op.create_index(op.f('ix_app_users_organization_id'), 'app_users', ['organization_id'], unique=False)
    op.create_table('notify_deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('membership_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('recipient', sa.String(), nullable=True),
    sa.Column('recipient_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('provider_message_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('body_preview', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notify_deliveries_id'), 'notify_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_notify_deliveries_meeting_id'), 'notify_deliveries', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_notify_deliveries_membership_id'), 'notify_deliveries', ['membership_id'], unique=False)
    op.create_index(op.f('ix_notify_deliveries_organization_id'), 'notify_deliveries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_notify_deliveries_provider_message_id'), 'notify_deliveries', ['provider_message_id'], unique=False)
    op.create_table('org_notify_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('smtp_enabled', sa.Boolean(), nullable=True),
    sa.Column('smtp_host', sa.String(), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_username', sa.String(), nullable=True),
    sa.Column('smtp_password_enc', sa.String(), nullable=True),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=True),
    sa.Column('smtp_use_ssl', sa.Boolean(), nullable=True),
    sa.Column('smtp_from_email', sa.String(), nullable=True),
    sa.Column('smtp_from_name', sa.String(), nullable=True),
    sa.Column('sms_enabled', sa.Boolean(), nullable=True),
    sa.Column('sms_api_key_enc', sa.String(), nullable=True),
    sa.Column('sms_line_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_notify_settings_id'), 'org_notify_settings', ['id'], unique=False)
    op.create_index(op.f('ix_org_notify_settings_organization_id'), 'org_notify_settings', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_notify_settings_organization_id'), table_name='org_notify_settings')
    op.drop_index(op.f('ix_org_notify_settings_id'), table_name='org_notify_settings')
    op.drop_table('org_notify_settings')
    op.drop_index(op.f('ix_notify_deliveries_provider_message_id'), table_name='notify_deliveries')
    op.drop_index(op.f('ix_notify_deliveries_organization_id'), table_name='notify_deliveries')
    op.drop_index(op.f('ix_notify_deliveries_membership_id'), table_name='notify_deliveries')
    op.drop_index(op.f('ix_notify_deliveries_meeting_id'), table_name='notify_deliveries')
    op.drop_index(op.f('ix_notify_deliveries_id'), table_name='notify_deliveries')
    op.drop_table('notify_deliveries')
    op.drop_index(op.f('ix_app_users_organization_id'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_national_id'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_id'), table_name='app_users')
    op.drop_table('app_users')
    # ### end Alembic commands ###