"""auto update

Revision ID: ed8588395a22
Revises: 830baecb4a38
Create Date: 2026-08-20 04:04:30.141375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed8588395a22'
down_revision: Union[str, Sequence[str], None] = '830baecb4a38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('object_key', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.String(), nullable=True),
    sa.Column('uploaded_by_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_attachments_id'), 'meeting_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_attachments_meeting_id'), 'meeting_attachments', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_attachments_organization_id'), 'meeting_attachments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_meeting_attachments_uploaded_by_user_id'), 'meeting_attachments', ['uploaded_by_user_id'], unique=False)
    op.create_table('org_ai_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('provider_key', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('api_key_enc', sa.String(), nullable=True),
    sa.Column('auth_username', sa.String(), nullable=True),
    sa.Column('auth_password_enc', sa.String(), nullable=True),
    sa.Column('diarization', sa.Boolean(), nullable=True),
    sa.Column('extra_json', sa.String(), nullable=True),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.Column('last_test_at', sa.String(), nullable=True),
    sa.Column('last_test_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_ai_providers_id'), 'org_ai_providers', ['id'], unique=False)
    op.create_index(op.f('ix_org_ai_providers_organization_id'), 'org_ai_providers', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_ai_providers_organization_id'), table_name='org_ai_providers')
    op.drop_index(op.f('ix_org_ai_providers_id'), table_name='org_ai_providers')
    op.drop_table('org_ai_providers')
    op.drop_index(op.f('ix_meeting_attachments_uploaded_by_user_id'), table_name='meeting_attachments')
    op.drop_index(op.f('ix_meeting_attachments_organization_id'), table_name='meeting_attachments')
    op.drop_index(op.f('ix_meeting_attachments_meeting_id'), table_name='meeting_attachments')
    op.drop_index(op.f('ix_meeting_attachments_id'), table_name='meeting_attachments')
    op.drop_table('meeting_attachments')
    # ### end Alembic commands ###